#!/bin/bash
# Usage: bash fix-config.sh variants/r/App.jsx
FILE="$1"
sed -i 's/const company = config\.company || {};//g' "$FILE"
sed -i 's/config\.company?\.phone\b/config.phone/g' "$FILE"
sed -i 's/config\.company?\.email\b/config.email/g' "$FILE"
sed -i 's/config\.company?\.address\b/config.address/g' "$FILE"
sed -i 's/config\.company?\.name\b/config.name/g' "$FILE"
sed -i 's/company\.phone\b/config.phone/g' "$FILE"
sed -i 's/company\.email\b/config.email/g' "$FILE"
sed -i 's/company\.address\b/config.address/g' "$FILE"
sed -i 's/company\.name\b/config.name/g' "$FILE"
sed -i 's/company\.description\b/config.description/g' "$FILE"
sed -i 's/config\.hero?\.heading\b/config.hero?.headline/g' "$FILE"
sed -i 's/config\.hero?\.subtitle\b/config.hero?.subheadline/g' "$FILE"
sed -i 's/{item\.question}/{item.question || item.q}/g' "$FILE"
sed -i 's/{item\.answer}/{item.answer || item.a}/g' "$FILE"
sed -i "s/const locations = config\.locations || \['[^']*'.*\];/const locations = (config.locations || []).map(l => l.name || l);/g" "$FILE"
echo "Fixed: $FILE"
