const siteConfig = {
  name: "Ulcinj Car Hire",
  tagline: "Drive Montenegro's Southern Coast",
  domain: "ulcinjcarhire.com",
  phone: "",
  email: "info@ulcinjcarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Explore Ulcinj at Your Own Pace",
    subheadline: "Affordable car hire near Velika Plaza. 40km from Podgorica Airport, 75km from Tivat Airport.",
    image: "/img/hero-ulcinj.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      typeGroup: "economy",
      name: "VW Polo",
      category: "Economy",
      tagline: "Simple hatch that parks anywhere outside Kalaja and sips petrol all the way to Ada Bojana",
      lede: "Five seats, 351-litre boot and a turning circle made for narrow lanes beneath the Ottoman walls.",
      price: 25,
      image: "/img/fleet/vw-polo.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      details: {
        engine: "1.0 L TSI 3-cyl turbo petrol",
        power: "95 hp",
        consumption: "5.2 L/100 km",
        bootSize: "351 L",
        length: "4,074 mm",
        topSpeed: "187 km/h",
        acceleration: "10.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples visiting Velika Plaža", "Short Albanian border hops", "Solo long-weekenders"],
      suitability: "Two travellers with cabin bags staying a short walk from Mala Plaža, easy to park outside the Stari Grad walls and cheap to run down to Sukobin and back.",
      regional: "Slots into the tight kerbs along Ulcinj's Boulevard Teuta and the makeshift parking beside Velika Plaža service roads. Nimble through the narrow alleys climbing up to Kalaja and composed on the coastal road north to Bar.",
    },
    {
      id: 2,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Tiny city car that fits between the lemon trees on the approach to Mala Plaža",
      lede: "Parks where nothing else fits, perfect when the old-town lanes fill up with summer traffic.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Solo beach-hoppers", "Photographers on the Stari Grad walls", "Short sunny stays"],
      suitability: "One or two travellers based near Mala Plaža who want the smallest car that will still take a day bag to Ada Bojana, distances are short, parking is scarce, the 500 thrives.",
      regional: "Slips into the angled bays along the Pristan promenade and the compact lots at the foot of Kalaja. The sunroof is worth the rental alone on the coast road north through the Valdanos olive groves at golden hour.",
    },
    {
      id: 3,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "Soft-riding French hatch that eats the coastal road from Ulcinj to Bar",
      lede: "391-litre boot, supple damping, cheap to fuel, the default Ulcinj week-long small car.",
      price: 26,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Apple CarPlay", "Rear Parking Sensors", "Cruise Control", "USB Charging"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.4 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "187 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["Couples on a one-week stay", "Velika Plaža day-trippers", "Shkodër border-hoppers"],
      suitability: "Two travellers basing near the Pristan promenade who want the biggest boot in the small-hatch class and a cabin that cruises the coast road north without feeling overmatched.",
      regional: "Soaks up the patched tarmac around Sutomore on the run north to Bar and handles the Sukobin border crossing into Albania with the composure you want on an unfamiliar road. Turning circle tight enough for Mala Plaža's angled bays.",
    },
    {
      id: 4,
      slug: "renault-megane",
      typeGroup: "midsize",
      name: "Renault Megane",
      category: "Mid-Size",
      tagline: "Family-size diesel hatch with the quietest cabin on the Ulcinj–Tivat haul",
      lede: "434-litre boot, 4.3 L/100 km diesel, soft long-distance ride, the car for the multi-city week.",
      price: 41,
      image: "/img/fleet/renault-megane.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["EDC Auto", "Adaptive Cruise", "Portrait Touchscreen", "Rear Climate Vents"],
      details: {
        engine: "1.5 Blue dCi diesel",
        power: "115 hp",
        consumption: "4.3 L/100 km",
        bootSize: "434 L (1,247 L seats folded)",
        length: "4,360 mm",
        topSpeed: "200 km/h",
        acceleration: "10.8s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd EDC auto",
      },
      popular: false,
      bestFor: ["Families of four with luggage", "Airport transfer return legs", "Long coast itineraries"],
      suitability: "Four travellers planning three nights in Ulcinj and three elsewhere, Budva, Kotor, or across the border in Shkodër, who want one quiet diesel for every leg and a boot that actually fits the family.",
      regional: "The EDC auto and diesel torque make short work of the inland climb over Sozina on the Podgorica run, and the long-travel damping smothers the broken edges on the service road to Velika Plaža. Rear vents matter on a four-up Ada Bojana day in August.",
    },
    {
      id: 5,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Hybrid that sips petrol through Ulcinj's 35°C summer traffic",
      lede: "Real-world 3.8 L/100 km, the cheapest car to run on long days between Sukobin and Valdanos.",
      price: 34,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drivetrain", "Reversing Camera", "Apple CarPlay", "Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-i Hybrid petrol–electric",
        power: "116 hp combined",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0–100 km/h)",
        driveType: "Front-wheel drive (e-CVT)",
      },
      popular: true,
      bestFor: ["Fuel-conscious travellers", "Stop-start beach days", "Longer coastal stays"],
      suitability: "Travellers who want two weeks of driving on a quarter-tank budget. The hybrid pays for itself on repeat trips between town, Velika Plaža and the Sukobin border.",
      regional: "The electric compressor keeps the cabin cold in July without loading the petrol engine, a quality-of-life advantage in Montenegro's hottest town. Pure-electric crawl past the Pristan cafés at dusk, then silent cruising along the Bar coastal road.",
    },
    {
      id: 6,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised ride height for the bumpy track down to Ada Bojana's stilt restaurants",
      lede: "352-litre boot, higher ride than a hatch, modest petrol, the sensible crossover for the south coast.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height", "Apple CarPlay", "Reversing Camera", "Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Kitesurfers with gear", "Couples heading inland", "Budget crossover renters"],
      suitability: "Renters who want a taller driving position and a bit more clearance without paying premium-SUV money, perfect if your week includes Ada Bojana, Šasko Lake and the Valdanos olive track.",
      regional: "The extra ride height handles the unpaved service roads between Velika Plaža access points and the rougher approach to Ada Bojana. Front-wheel drive only, pick this over a hatch for loose surfaces, not over a proper 4x4 for winter trips inland.",
    },
    {
      id: 7,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Taut French mid-size diesel for the airport-run-plus-beach-week double duty",
      lede: "412-litre boot, 4.4 L/100 km BlueHDi, i-Cockpit cabin, the composed pick for the long legs.",
      price: 44,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["EAT8 Auto", "Adaptive Cruise", "i-Cockpit", "Apple CarPlay"],
      details: {
        engine: "1.5 BlueHDi diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,323 L seats folded)",
        length: "4,367 mm",
        topSpeed: "207 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd EAT auto",
      },
      popular: true,
      bestFor: ["Airport transfer runs", "Cross-border day trips", "Families doing the full south coast"],
      suitability: "The pick when the Ulcinj week is really a regional tour, three nights in town, a day in Shkodër, a long return up to Tivat Airport, and you want one car that handles every leg without complaint.",
      regional: "The diesel torque and 8-speed auto eat the climb over Sozina on the Podgorica approach and the adaptive cruise keeps the coastal run to Budva honest in slow Bar truck traffic. i-Cockpit suits tall drivers who want to look over rather than through the steering wheel.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Beach Access", description: "Velika Plaza, Ada Bojana, Valdanos, each beach a different world, and none of them on a bus route." },
    { icon: "shield-check", title: "Full Insurance", description: "Comprehensive coverage with zero excess option. Includes protection on unpaved access roads near Ada Bojana and the Valdanos olive grove track." },
    { icon: "clock", title: "24/7 Support", description: "Kite snapped at Ada Bojana and you need a lift? Ring us. Roadside help available around the clock, wherever the road ends." },
    { icon: "ban", title: "No Hidden Fees", description: "Everything baked into the price, including the longer airport transfer from Podgorica (2 hrs) or Tivat (2.5 hrs). What you see is what you pay." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Wind conditions shift and kitesurfing plans change. Cancel up to 24 hours before pickup for a full refund, seasonal changes covered too." },
    { icon: "globe", title: "Cross-Border", description: "Albania is 20 minutes away, the Muriqan/Sukobin crossing is the closest entry point from Montenegro. Shkodra in 45 min, Tirana in 3 hrs. Croatia, Kosovo, and Bosnia also permitted." },
  ],

  testimonials: [
    { name: "Lukas Brandt", location: "Hamburg, Germany", text: "I came for the Ada Bojana wind and it delivered, three straight days of kiting in near-perfect thermals. Having the car meant I could scout the beach from both sides and still drive up the coast for dinner in Ulcinj each evening. Wouldn't have done it any other way.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Marta & Piotr", location: "Kraków, Poland", text: "We spent our mornings wandering the Ottoman walls of Stari Grad and our evenings driving out to Velika Plaza to watch the sun drop into the Adriatic. The road along the coast at sunset is something we still talk about. The car made the whole rhythm of the trip possible.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Thabo Nkosi", location: "Cape Town, South Africa", text: "I crossed into Albania on day two, 20 minutes to the border, another 30 to Shkodra. It felt like a completely different world. Ulcinj itself already feels remote and unhurried compared to the rest of Montenegro's coast, but with wheels you can push even further south. Incredible region.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "Can I drop off at a different location?", a: "Yes, one-way rentals are available across 28 towns and cities throughout Montenegro. Given the distance from both airports, picking up at Podgorica or Tivat and returning the car in Ulcinj (or the reverse) is one of the most popular combinations we arrange." },
    { q: "How does pickup work?", a: "Ulcinj is around 2 hours from Podgorica Airport and 2.5 hours from Tivat, both are long drives after a flight. We strongly recommend a one-way rental: pick up at whichever airport you land at and drop off in Ulcinj, or vice versa. Pick up times and meeting points are confirmed with the rental agent after booking." },
    { q: "What documents do I need?", a: "A valid driving licence showing details in Latin script, your passport, and a physical credit card in the main driver's name. If your licence was issued outside the EU and is only valid in its country of origin, bring an International Driving Permit. Electronic or photocopied licences are not accepted at pickup." },
    { q: "Can I drive to Albania?", a: "Absolutely, and Ulcinj is the best starting point in Montenegro for it. The Muriqan/Sukobin border crossing is just 20 minutes south of town and usually clears quickly. Shkodra is 45 minutes away; Tirana is around 3 hours. Just tell us at booking and we'll have the Green Card and border paperwork ready. Travel to Croatia, Bosnia, Kosovo, and Serbia is also permitted." },
    { q: "Is there a minimum age?", a: "The minimum age is 21. Drivers must have held a full licence for at least 2 years. Drivers aged 21–24 pay a young driver supplement, the exact rate is shown per vehicle in the search results." },
    { q: "What's included in the price?", a: "All vehicles include Third Party Liability insurance and Collision Damage Waiver (CDW) in the base price. VAT, mandatory equipment kit (first aid, warning triangle, visibility vest), and a transparent fuel policy are all included. Note that fuel stations become sparse south of Bar, tank up before heading to Ada Bojana or Valdanos. Unlimited mileage and extended coverage upgrades are available per vehicle." },
    { q: "What is the cancellation policy?", a: "Standard rentals: free cancellation up to 7 days before the start date. Premium and convertible vehicles: free cancellation up to 30 days before. A 6% payment processing fee applies to all cancellations regardless of timing. If you're planning around kitesurfing conditions at Ada Bojana, the flexible cancellation window is worth keeping in mind." },
    { q: "Is a deposit required?", a: "Deposit requirements vary by vehicle, typically between EUR 50 and EUR 300, and some cars carry no deposit at all. The deposit must be on a physical credit card (not debit or prepaid) in the main driver's name. It is held at pickup and released within a few business days of returning the vehicle undamaged." },
    { q: "What happens if I exceed the mileage limit?", a: "Vehicles that carry a mileage cap charge per kilometre above the agreed limit. The per-km rate is listed in the vehicle details before you confirm your booking. If you're planning to drive into Albania or explore the full Montenegrin coast, look for unlimited mileage options in the search results." },
    { q: "Are there any hidden fees?", a: "None. The price shown at booking is the full price, taxes, VAT, and all standard fees are included. The longer transfer from Podgorica or Tivat is factored in, not added on. You won't be handed a surprise invoice at pickup." },
    { q: "How much do I pay upfront?", a: "A deposit of 15–20% of the total rental cost is taken at booking to secure the vehicle. The remaining balance is settled in cash or by card directly with the rental agent when you collect the keys." },
    { q: "Can I rent without a credit card?", a: "A small selection of vehicles can be rented without a credit card. These are flagged clearly in the search results. For most vehicles, particularly those available with zero deposit, a physical credit card in the main driver's name is required." },
  ],

  locations: [
    { name: "Ulcinj Old Town", tag: "Most Popular" },
    { name: "Velika Plaza", tag: "Long Beach" },
    { name: "Ada Bojana", tag: "Kitesurfing" },
  ],

  destinations: [
    {
      name: "Velika Plaza",
      slug: "velika-plaza",
      tag: "Long Beach",
      desc: "12km of sandy coastline, one of Europe's longest beaches.",
      image: "/img/velika-plaza.webp",
    },
    {
      name: "Ada Bojana",
      slug: "ada-bojana",
      tag: "Kitesurfing",
      desc: "River island with sandy beaches and consistent wind.",
      image: "/img/ada-bojana.webp",
    },
    {
      name: "Stari Grad",
      slug: "stari-grad",
      tag: "Old Town",
      desc: "Ancient fortress and Ottoman architecture overlooking the sea.",
      image: "/img/ulcinj-old-town.webp",
    },
    {
      name: "Valdanos",
      slug: "valdanos",
      tag: "Olive Groves",
      desc: "Secluded bay surrounded by 80,000 olive trees.",
      image: "/img/valdanos-olives.webp",
    },
    {
      name: "Bar",
      slug: "bar",
      tag: "30 Minutes",
      desc: "Port city with Stari Bar ruins and ferry connections.",
      image: "/img/bar-nearby.webp",
    },
    {
      name: "Lake Skadar",
      slug: "lake-skadar",
      tag: "45 Minutes",
      desc: "The Balkans' largest lake, pelicans, monasteries, wine.",
      image: "/img/lake-skadar.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "40 Minutes",
      desc: "Montenegro's closest airport to Ulcinj.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Shkodra",
      slug: "shkodra",
      tag: "Albania, 30 Min",
      desc: "Cross into Albania and explore Rozafa Castle.",
      image: "/img/shkodra-albania.webp",
    },
  ],
};

export default siteConfig;
