const siteConfig = {
  name: "Ulcinj Car Hire",
  tagline: "Drive Montenegro's Southern Coast",
  domain: "ulcinjcarhire.com",
  phone: "",
  email: "info@ulcinjcarhire.com",
  address: "Ulcinj, Montenegro",

  hero: {
    headline: "Explore Ulcinj at Your Own Pace",
    subheadline: "Affordable car hire near Velika Plaza. 40km from Podgorica Airport, 75km from Tivat Airport.",
    image: "/img/pexels-3802510.jpg",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Beach Access", description: "Drive straight to Velika Plaza, Ada Bojana, or Valdanos. No taxis needed." },
    { icon: "shield-check", title: "Full Insurance", description: "Comprehensive coverage with zero excess option. Drive with complete peace of mind." },
    { icon: "clock", title: "24/7 Support", description: "Roadside assistance and customer service available around the clock, every day." },
    { icon: "ban", title: "No Hidden Fees", description: "Fuel policy, mileage, tax — everything is included in the price you see." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Plans change. Cancel up to 24 hours before pickup for a full refund." },
    { icon: "globe", title: "Cross-Border", description: "Drive to Albania, Croatia, Bosnia, or Kosovo. Cross-border travel permitted." },
  ],

  testimonials: [
    { name: "James Hartley", location: "Bristol, UK", text: "Ulcinj is far from both airports so a hire car was essential. Picked up at Podgorica and drove straight to Long Beach. Painless experience.", rating: 5, avatar: "/img/pexels-220453.jpg" },
    { name: "Anna Fischer", location: "Munich, Germany", text: "We drove from Tivat down to Ada Bojana for the kitesurfing. The car was in great condition and we crossed into Albania for a day trip to Shkodra. Brilliant.", rating: 5, avatar: "/img/pexels-774909.jpg" },
    { name: "Tom & Sarah", location: "Melbourne, Australia", text: "Spent a week exploring Ulcinj's Old Town and the olive groves at Valdanos. Without a car you'd miss all of it — public transport barely exists down here.", rating: 5, avatar: "/img/pexels-1222271.jpg" },
  ],

  faq: [
    { q: "What documents do I need?", a: "A valid driving licence, passport or ID, and a credit card in the main driver's name. International Driving Permit required for non-EU licences." },
    { q: "Can I drive to Albania?", a: "Yes! Cross-border travel is permitted to Albania, Croatia, Bosnia, Kosovo, and Serbia. Just let us know at booking and we'll prepare the Green Card." },
    { q: "Is there a minimum age?", a: "The minimum age is 21 with at least 2 years driving experience. Drivers under 25 pay a small young driver supplement of EUR5/day." },
    { q: "What's included in the price?", a: "Full insurance (CDW + theft protection), unlimited mileage, VAT, airport pickup/dropoff, 24/7 roadside assistance, and a free second driver." },
    { q: "How does pickup work at the airport?", a: "We meet you at the arrivals hall with your name on a sign. Your car is parked right outside. Total time from landing to driving: about 10 minutes." },
    { q: "Can I drop off at a different location?", a: "Yes — one-way rentals are supported across 28 cities and towns in Montenegro. Simply choose different pickup and dropoff locations during booking." },
    { q: "Can I cancel my booking?", a: "Free cancellation up to 7 days before the rental start date. For luxury cars and convertibles, free cancellation is available up to 30 days before. A 6% payment service fee applies to all cancellations." },
    { q: "Is a deposit required?", a: "Deposits range from EUR50 to EUR300 depending on the vehicle. Some cars are available with no deposit. The deposit must be on a physical credit card in the driver's name and is refunded upon return of the vehicle in good condition." },
    { q: "What happens if I exceed the mileage limit?", a: "For vehicles with a mileage limit, an additional charge per extra kilometre applies above the agreed limit. The rate is specified in the rental terms for the vehicle." },
    { q: "Are there hidden costs?", a: "The final rental price includes all taxes and fees — there are no hidden costs." },
    { q: "How much is the down payment?", a: "A down payment of 15-20% is required to confirm your booking. The remaining balance is paid to the rental company at pickup." },
    { q: "Can I rent without a credit card?", a: "Some vehicles can be rented without a credit card — available options are marked in the search results." },
  ],

  locations: [
    { name: "Ulcinj Old Town", tag: "Most Popular" },
    { name: "Velika Plaza", tag: "Long Beach" },
    { name: "Ada Bojana", tag: "Kitesurfing" },
  ],

  destinations: [
    {
      name: "Velika Plaza",
      slug: "velika-plaza",
      tag: "Long Beach",
      desc: "12km of sandy coastline — one of Europe's longest beaches.",
      image: "/img/pexels-3802510.jpg",
    },
    {
      name: "Ada Bojana",
      slug: "ada-bojana",
      tag: "Kitesurfing",
      desc: "River island with sandy beaches and consistent wind.",
      image: "/img/pexels-16099591.jpg",
    },
    {
      name: "Stari Grad",
      slug: "stari-grad",
      tag: "Old Town",
      desc: "Ancient fortress and Ottoman architecture overlooking the sea.",
      image: "/img/pexels-5668157.jpg",
    },
    {
      name: "Valdanos",
      slug: "valdanos",
      tag: "Olive Groves",
      desc: "Secluded bay surrounded by 80,000 olive trees.",
      image: "/img/pexels-9526645.jpg",
    },
    {
      name: "Bar",
      slug: "bar",
      tag: "30 Minutes",
      desc: "Port city with Stari Bar ruins and ferry connections.",
      image: "/img/pexels-26753897.jpg",
    },
    {
      name: "Lake Skadar",
      slug: "lake-skadar",
      tag: "45 Minutes",
      desc: "The Balkans' largest lake — pelicans, monasteries, wine.",
      image: "/img/pexels-28674522.jpg",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "40 Minutes",
      desc: "Montenegro's closest airport to Ulcinj.",
      image: "/img/pexels-29904099.jpg",
    },
    {
      name: "Shkodra",
      slug: "shkodra",
      tag: "Albania — 30 Min",
      desc: "Cross into Albania and explore Rozafa Castle.",
      image: "/img/pexels-6216512.jpg",
    },
  ],
};

export default siteConfig;
